# coding: utf-8

"""
    pyDataverse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from pyDataverse.models.role_dto import RoleDTO  # noqa: E501

class TestRoleDTO(unittest.TestCase):
    """RoleDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoleDTO:
        """Test RoleDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoleDTO`
        """
        model = RoleDTO()  # noqa: E501
        if include_optional:
            return RoleDTO(
                alias = '',
                name = '',
                description = '',
                owner_id = '',
                permissions = ''
            )
        else:
            return RoleDTO(
        )
        """

    def testRoleDTO(self):
        """Test RoleDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
