# coding: utf-8

"""
    pyDataverse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from pyDataverse.models.role_assignment_dto import RoleAssignmentDTO  # noqa: E501

class TestRoleAssignmentDTO(unittest.TestCase):
    """RoleAssignmentDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoleAssignmentDTO:
        """Test RoleAssignmentDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoleAssignmentDTO`
        """
        model = RoleAssignmentDTO()  # noqa: E501
        if include_optional:
            return RoleAssignmentDTO(
                assignee = '',
                role = ''
            )
        else:
            return RoleAssignmentDTO(
        )
        """

    def testRoleAssignmentDTO(self):
        """Test RoleAssignmentDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
