"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional


@dataclasses.dataclass
class CreateNewRoleRequest:
    dvo: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'dvo', 'style': 'form', 'explode': True }})
    request_body: Optional[bytes] = dataclasses.field(default=None, metadata={'request': { 'media_type': '*/*' }})
    



@dataclasses.dataclass
class CreateNewRoleResponseBody:
    r"""Default Response."""
    



@dataclasses.dataclass
class CreateNewRoleResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    body: Optional[bytes] = dataclasses.field(default=None)
    

