"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional


@dataclasses.dataclass
class ExportDatasetRequest:
    exporter: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'exporter', 'style': 'form', 'explode': True }})
    persistent_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'persistentId', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class ExportDatasetNativeResponseDefaultResponseBody:
    r"""Default Response."""
    



@dataclasses.dataclass
class ExportDatasetNativeResponseBody:
    r"""Default Response."""
    



@dataclasses.dataclass
class ExportDatasetResponseBody:
    r"""Default Response."""
    



@dataclasses.dataclass
class ExportDatasetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    body: Optional[bytes] = dataclasses.field(default=None)
    default_application_json_object: Optional[ExportDatasetNativeResponseBody] = dataclasses.field(default=None)
    r"""Default Response."""
    default_application_ld_plus_json_object: Optional[ExportDatasetNativeResponseDefaultResponseBody] = dataclasses.field(default=None)
    r"""Default Response."""
    

