"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional


@dataclasses.dataclass
class GetFileMetadataRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    version_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'versionId', 'style': 'form', 'explode': True }})
    request_body: Optional[bytes] = dataclasses.field(default=None, metadata={'request': { 'media_type': '*/*' }})
    



@dataclasses.dataclass
class GetFileMetadataResponseBody:
    r"""Default Response."""
    



@dataclasses.dataclass
class GetFileMetadataResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    body: Optional[bytes] = dataclasses.field(default=None)
    

