"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from typing import Optional


@dataclasses.dataclass
class RoleAssignmentDTO:
    assignee: Optional[str] = dataclasses.field(default=None)
    role: Optional[str] = dataclasses.field(default=None)
    

