/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type GetBlockRequest = {
    identifier: string;
};

/**
 * Default Response.
 */
export type GetBlockResponseBody = {};

export type GetBlockResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Default Response.
     */
    object?: GetBlockResponseBody | undefined;
};

/** @internal */
export namespace GetBlockRequest$ {
    export type Inbound = {
        identifier: string;
    };

    export const inboundSchema: z.ZodType<GetBlockRequest, z.ZodTypeDef, Inbound> = z
        .object({
            identifier: z.string(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
            };
        });

    export type Outbound = {
        identifier: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBlockRequest> = z
        .object({
            identifier: z.string(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
            };
        });
}

/** @internal */
export namespace GetBlockResponseBody$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<GetBlockResponseBody, z.ZodTypeDef, Inbound> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBlockResponseBody> = z.object(
        {}
    );
}

/** @internal */
export namespace GetBlockResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: GetBlockResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetBlockResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => GetBlockResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: GetBlockResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBlockResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => GetBlockResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
