/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64";
import { z } from "zod";

export type ImportDatasetRequest = {
    identifier: string;
    pid?: string | undefined;
    release?: string | undefined;
    requestBody?: string | undefined;
};

/**
 * Default Response.
 */
export type ImportDatasetResponseBody = {};

export type ImportDatasetResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    body?: Uint8Array | string | undefined;
};

/** @internal */
export namespace ImportDatasetRequest$ {
    export type Inbound = {
        identifier: string;
        pid?: string | undefined;
        release?: string | undefined;
        RequestBody?: string | undefined;
    };

    export const inboundSchema: z.ZodType<ImportDatasetRequest, z.ZodTypeDef, Inbound> = z
        .object({
            identifier: z.string(),
            pid: z.string().optional(),
            release: z.string().optional(),
            RequestBody: z.string().optional(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
                ...(v.pid === undefined ? null : { pid: v.pid }),
                ...(v.release === undefined ? null : { release: v.release }),
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        identifier: string;
        pid?: string | undefined;
        release?: string | undefined;
        RequestBody?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ImportDatasetRequest> = z
        .object({
            identifier: z.string(),
            pid: z.string().optional(),
            release: z.string().optional(),
            requestBody: z.string().optional(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
                ...(v.pid === undefined ? null : { pid: v.pid }),
                ...(v.release === undefined ? null : { release: v.release }),
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace ImportDatasetResponseBody$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<ImportDatasetResponseBody, z.ZodTypeDef, Inbound> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ImportDatasetResponseBody> =
        z.object({});
}

/** @internal */
export namespace ImportDatasetResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        Body?: Uint8Array | string | undefined;
    };

    export const inboundSchema: z.ZodType<ImportDatasetResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            Body: b64$.zodInbound.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.Body === undefined ? null : { body: v.Body }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        Body?: Uint8Array | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ImportDatasetResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            body: b64$.zodOutbound.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.body === undefined ? null : { Body: v.body }),
            };
        });
}
