/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64";
import { z } from "zod";

export type ListRolesRequest = {
    identifier: string;
};

/**
 * Default Response.
 */
export type ListRolesResponseBody = {};

export type ListRolesResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    body?: Uint8Array | string | undefined;
};

/** @internal */
export namespace ListRolesRequest$ {
    export type Inbound = {
        identifier: string;
    };

    export const inboundSchema: z.ZodType<ListRolesRequest, z.ZodTypeDef, Inbound> = z
        .object({
            identifier: z.string(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
            };
        });

    export type Outbound = {
        identifier: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListRolesRequest> = z
        .object({
            identifier: z.string(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
            };
        });
}

/** @internal */
export namespace ListRolesResponseBody$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<ListRolesResponseBody, z.ZodTypeDef, Inbound> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListRolesResponseBody> =
        z.object({});
}

/** @internal */
export namespace ListRolesResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        Body?: Uint8Array | string | undefined;
    };

    export const inboundSchema: z.ZodType<ListRolesResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            Body: b64$.zodInbound.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.Body === undefined ? null : { body: v.Body }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        Body?: Uint8Array | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListRolesResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            body: b64$.zodOutbound.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.body === undefined ? null : { Body: v.body }),
            };
        });
}
