/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type SetFacetsRequest = {
    identifier: string;
    requestBody?: string | undefined;
};

/**
 * Default Response.
 */
export type SetFacetsResponseBody = {};

export type SetFacetsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Default Response.
     */
    object?: SetFacetsResponseBody | undefined;
};

/** @internal */
export namespace SetFacetsRequest$ {
    export type Inbound = {
        identifier: string;
        RequestBody?: string | undefined;
    };

    export const inboundSchema: z.ZodType<SetFacetsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            identifier: z.string(),
            RequestBody: z.string().optional(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        identifier: string;
        RequestBody?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SetFacetsRequest> = z
        .object({
            identifier: z.string(),
            requestBody: z.string().optional(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace SetFacetsResponseBody$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<SetFacetsResponseBody, z.ZodTypeDef, Inbound> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SetFacetsResponseBody> =
        z.object({});
}

/** @internal */
export namespace SetFacetsResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: SetFacetsResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<SetFacetsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => SetFacetsResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: SetFacetsResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SetFacetsResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => SetFacetsResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
