/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64";
import { z } from "zod";

export type UpdateDraftVersionRequest = {
    id: string;
    versionId: string;
    requestBody?: string | undefined;
};

/**
 * Default Response.
 */
export type UpdateDraftVersionResponseBody = {};

export type UpdateDraftVersionResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    body?: Uint8Array | string | undefined;
};

/** @internal */
export namespace UpdateDraftVersionRequest$ {
    export type Inbound = {
        id: string;
        versionId: string;
        RequestBody?: string | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateDraftVersionRequest, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string(),
            versionId: z.string(),
            RequestBody: z.string().optional(),
        })
        .transform((v) => {
            return {
                id: v.id,
                versionId: v.versionId,
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        id: string;
        versionId: string;
        RequestBody?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateDraftVersionRequest> = z
        .object({
            id: z.string(),
            versionId: z.string(),
            requestBody: z.string().optional(),
        })
        .transform((v) => {
            return {
                id: v.id,
                versionId: v.versionId,
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace UpdateDraftVersionResponseBody$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<UpdateDraftVersionResponseBody, z.ZodTypeDef, Inbound> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateDraftVersionResponseBody> =
        z.object({});
}

/** @internal */
export namespace UpdateDraftVersionResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        Body?: Uint8Array | string | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateDraftVersionResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            Body: b64$.zodInbound.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.Body === undefined ? null : { body: v.Body }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        Body?: Uint8Array | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateDraftVersionResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            body: b64$.zodOutbound.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.body === undefined ? null : { Body: v.body }),
            };
        });
}
