# coding: utf-8

"""
    pyDataverse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyDataverse.api.native_api import NativeApi


class TestNativeApi(unittest.TestCase):
    """NativeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NativeApi()

    def tearDown(self) -> None:
        pass

    def test_add_dataverse(self) -> None:
        """Test case for add_dataverse

        """
        pass

    def test_add_file_to_dataset(self) -> None:
        """Test case for add_file_to_dataset

        """
        pass

    def test_create_assignment(self) -> None:
        """Test case for create_assignment

        """
        pass

    def test_create_new_role(self) -> None:
        """Test case for create_new_role

        """
        pass

    def test_create_private_url(self) -> None:
        """Test case for create_private_url

        """
        pass

    def test_create_role(self) -> None:
        """Test case for create_role

        """
        pass

    def test_delete_dataset(self) -> None:
        """Test case for delete_dataset

        """
        pass

    def test_delete_dataverse(self) -> None:
        """Test case for delete_dataverse

        """
        pass

    def test_delete_draft_version(self) -> None:
        """Test case for delete_draft_version

        """
        pass

    def test_delete_file_in_dataset(self) -> None:
        """Test case for delete_file_in_dataset

        """
        pass

    def test_delete_private_url(self) -> None:
        """Test case for delete_private_url

        """
        pass

    def test_delete_role(self) -> None:
        """Test case for delete_role

        """
        pass

    def test_delete_token(self) -> None:
        """Test case for delete_token

        """
        pass

    def test_destroy_dataset(self) -> None:
        """Test case for destroy_dataset

        """
        pass

    def test_edit_version_metadata(self) -> None:
        """Test case for edit_version_metadata

        """
        pass

    def test_export_dataset(self) -> None:
        """Test case for export_dataset

        """
        pass

    def test_get_assignments(self) -> None:
        """Test case for get_assignments

        """
        pass

    def test_get_authenticated_user_by_token(self) -> None:
        """Test case for get_authenticated_user_by_token

        """
        pass

    def test_get_block(self) -> None:
        """Test case for get_block

        """
        pass

    def test_get_dataset(self) -> None:
        """Test case for get_dataset

        """
        pass

    def test_get_dataset_by_pid(self) -> None:
        """Test case for get_dataset_by_pid

        """
        pass

    def test_get_file_data(self) -> None:
        """Test case for get_file_data

        """
        pass

    def test_get_file_metadata(self) -> None:
        """Test case for get_file_metadata

        """
        pass

    def test_get_info(self) -> None:
        """Test case for get_info

        """
        pass

    def test_get_private_url_data(self) -> None:
        """Test case for get_private_url_data

        """
        pass

    def test_get_server(self) -> None:
        """Test case for get_server

        """
        pass

    def test_get_terms_of_use(self) -> None:
        """Test case for get_terms_of_use

        """
        pass

    def test_get_token_expiration_date(self) -> None:
        """Test case for get_token_expiration_date

        """
        pass

    def test_get_version(self) -> None:
        """Test case for get_version

        """
        pass

    def test_import_dataset(self) -> None:
        """Test case for import_dataset

        """
        pass

    def test_list(self) -> None:
        """Test case for list

        """
        pass

    def test_list_content(self) -> None:
        """Test case for list_content

        """
        pass

    def test_list_facets(self) -> None:
        """Test case for list_facets

        """
        pass

    def test_list_roles(self) -> None:
        """Test case for list_roles

        """
        pass

    def test_list_versions(self) -> None:
        """Test case for list_versions

        """
        pass

    def test_publish_dataverse(self) -> None:
        """Test case for publish_dataverse

        """
        pass

    def test_recreate_token(self) -> None:
        """Test case for recreate_token

        """
        pass

    def test_redetect_datafile(self) -> None:
        """Test case for redetect_datafile

        """
        pass

    def test_reingest(self) -> None:
        """Test case for reingest

        """
        pass

    def test_replace_file_in_dataset(self) -> None:
        """Test case for replace_file_in_dataset

        """
        pass

    def test_restrict_file_in_dataset(self) -> None:
        """Test case for restrict_file_in_dataset

        """
        pass

    def test_set_facets(self) -> None:
        """Test case for set_facets

        """
        pass

    def test_uningest_datafile(self) -> None:
        """Test case for uningest_datafile

        """
        pass

    def test_update_draft_version(self) -> None:
        """Test case for update_draft_version

        """
        pass

    def test_update_file_metadata(self) -> None:
        """Test case for update_file_metadata

        """
        pass

    def test_view_dataverse(self) -> None:
        """Test case for view_dataverse

        """
        pass

    def test_view_role(self) -> None:
        """Test case for view_role

        """
        pass


if __name__ == '__main__':
    unittest.main()
